# Generated by Django 4.1.1 on 2022-11-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproject',
            name='project_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createproject',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
