# Generated by Django 4.1.1 on 2022-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_createproject_project_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(max_length=264)),
                ('employee_last_name', models.CharField(max_length=264)),
                ('employee_email', models.EmailField(blank=True, max_length=264, null=True, unique=True)),
                ('employee_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_description', models.CharField(max_length=264)),
                ('employee_own_bus', models.BooleanField(blank=True, null=True)),
                ('employee_own_tool', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='createproject',
            name='project_address',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='createproject',
            name='project_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
