# Generated by Django 4.1.1 on 2022-11-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_createemployee_alter_createproject_project_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.createemployee')),
            ],
        ),
    ]
