# Generated by Django 4.1.1 on 2022-11-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_uploadactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='project_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='uploadactivity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.createproject'),
        ),
    ]
