# Generated by Django 4.1.1 on 2022-11-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_uploadactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadactivity',
            name='image_3_comments',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='uploadactivity',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
