# Generated by Django 4.1.1 on 2022-11-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_uploadactivity_image_3_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadactivity',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
