# Generated by Django 4.1.1 on 2022-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_alter_uploadactivity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadactivity',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
