# Generated by Django 4.1.1 on 2022-11-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_alter_uploadactivity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadactivity',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadactivity',
            name='date_created_system',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
