# Generated by Django 4.1.1 on 2022-11-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_alter_uploadactivity_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looptest', models.CharField(max_length=264, null=True, unique=True)),
            ],
        ),
    ]
