# Generated by Django 4.1.1 on 2022-11-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_looptest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looptest',
            name='looptest',
        ),
        migrations.AddField(
            model_name='looptest',
            name='variable',
            field=models.CharField(default='hello', max_length=264),
            preserve_default=False,
        ),
    ]
