# Generated by Django 4.1.1 on 2022-11-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_remove_looptest_looptest_looptest_variable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoopTest',
        ),
    ]
